name: Build

on:
  push:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - uses: warrenbuckley/Setup-Nuget@v1
        with:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - run: nuget restore $Env:GITHUB_WORKSPACE\ControlWindowsServiceFromDiscord\ControlWindowsServiceFromDiscord.csproj
      - uses: warrenbuckley/Setup-MSBuild@v1
        with:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - run: MSBuild.exe $Env:GITHUB_WORKSPACE\ControlWindowsServiceFromDiscord\ControlWindowsServiceFromDiscord.csproj -p:Configuration=Release
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: artifacts
          path: ControlWindowsServiceFromDiscord\bin\Release
